### ISSUE TITLE
Countdown for start of game not working

### ISSUE THREAD

**Issue by xenamakky** [xenamakky/hungry-turtle-game#1]
I'm new here and publishing my first issue. I have a countdown for the game to start, but it doesn't actually count down.

**Comment by poohcom1** [comment]
Hey xenamakky, I'm interested in helping out with this! 

I actually found this repo because of Hacktoberfest, which is an event that encourages devs around the world to contribute to open-source.  If you don't mind, could you add the `hacktoberfest-accepted` label to the pull-request, so it can be a part of the event? 

Cheers
